version: "3"
services:
  mongo:
    image: mongo
    ports:
    - ${MONGO_PORT}:${MONGO_PORT}

  api:
    image: mmbarek/hijri-calendar-api:${API_TAG}
    expose:
      - ${API_SERVER_PORT}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    depends_on:
      - mongo
    environment:
      - SERVER_PORT=${API_SERVER_PORT}
      - MONGO_HOST
      - MONGO_PORT
  app:
    image: mmbarek/hijri-calendar:${APP_TAG}
    expose:
      - 80
    ports:
      - ${APP_SERVER_PORT}:80


